"""Initial migration

Revision ID: 182df9a500b2
Revises: e65b4d130fcc
Create Date: 2025-02-17 03:02:03.683463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182df9a500b2'
down_revision = 'e65b4d130fcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
