"""Initial migration

Revision ID: 8969744e1793
Revises: 182df9a500b2
Create Date: 2025-02-17 03:03:48.496514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8969744e1793'
down_revision = '182df9a500b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
