"""improved threat catalog

Revision ID: df938b81f264
Revises: f63492635f21
Create Date: 2025-02-17 21:56:00.770565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df938b81f264'
down_revision = 'f63492635f21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
