"""improved threat catalog

Revision ID: f63492635f21
Revises: 8969744e1793
Create Date: 2025-02-17 20:31:10.217105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63492635f21'
down_revision = '8969744e1793'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
